name: pypi
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.1.10
          virtualenvs-create: true
      - name: Pypi Publish
        run: poetry publish --no-interaction -vvv --build --username ${{secrets.PYPI_USER}} --password ${{secrets.PYPI_PASSWORD}}