name: pypi
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.1.10
          virtualenvs-create: true
      - name: Pypi Publish
        env:
          PYPI_USER: ${{ secrets.PYPI_USER }}
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          ls - l
          echo 'Building my package'
          poetry build
          echo 'finished build time to publish'
          echo 'started publishing'
          poetry publish --username $PYPI_USER --password $PYPI_PASSWORD
          echo 'module published successfully install now through pip and check'